version: '3.3'
services:
    app:
        build:
            context: ./app
        ports:
            - "8000:8000"
    nginx:
        build:
            context: ./nginx
        ports:
            - "80:80"
        links:
            - app
        
